import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Provider as ChakraProvider } from "@/components/ui/provider"
import { MetaMaskProvider } from "@/contexts/MetaMaskContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body 
        className={`${geistSans.variable} ${geistMono.variable}`}
        style={{
          backgroundImage: "url('/background_1300.png')",
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          overflow: "hidden",
          minHeight: "100vh",
        }}
      >
        <ChakraProvider>
          <MetaMaskProvider>
          {children}
          </MetaMaskProvider>
        </ChakraProvider>
      </body>
    </html>
  );
}
